-- AlterTable
ALTER TABLE "Potrero" ADD COLUMN     "gridH" INTEGER NOT NULL DEFAULT 1,
ADD COLUMN     "gridW" INTEGER NOT NULL DEFAULT 1,
ADD COLUMN     "gridX" INTEGER,
ADD COLUMN     "gridY" INTEGER;
